name: Stage

env:
  ENVIROMENT: blue
  DOCKER_IMAGE_NAME: api-dro-psypra-com
  PORTAINER_PROJECT_NAME: api_dro_psypra_com
  API_URL: 'https://dro.psypra.com/api'

on:
  push:
    branches: [main]

jobs:
  check:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install Dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run typescript type check
        run: npm run lint:types

      - name: Run test
        run: npm run test

  build:
    name: Build container
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_NAME: api
          envkey_NODE_ENV: production
          envkey_API_URL: ${{ env.API_URL }}
          envkey_API_PORT: 3001
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_JWT_EXP: 1d
          envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

  redeploy:
    name: Redeploy stack to Portainer
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Redeploy stack
        uses: luminos-company/portami@v1.2
        with:
          endpoint: '${{ secrets.PORTAINER_ENDPOINT }}'
          access_token: ${{ secrets.PORTAINER_ACCESS_TOKEN }}
          stack_name: '${{ env.PORTAINER_PROJECT_NAME }}_${{ env.ENVIROMENT }}'
          file_path: '.github/stack/${{ env.ENVIROMENT }}.yml'
          prune: true
          pull: true
