name: Stage

on:
  push:
    branches: [main]

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NODE_ENV: production
          envkey_API_PORT: 3001
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_JWT_EXP: 1d
          envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: shatynska/api-dro-psypra-com:latest

  redeploy:
    name: Redeploy stack to Portainer
    runs-on: ubuntu-latest
    needs: build-container
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Redeploy stack
        uses: luminos-company/portami@v1.1
        with:
          endpoint: "https://admin.psypra.com"
          access_token: ${{ secrets.PORTAINER_ACCESS_TOKEN }}
          stack_id: "api_dro_psypra_com_blue"
          file_path: ".github/stack/blue.yml"
          prune: true
          pull: true
